FROM node:20-alpine3.18

WORKDIR /opt
RUN echo '{ "name": "test-esl" }' > package.json
RUN yarn add -D typescript coffeescript @types/node ava uuid ulidx

# Build esl
WORKDIR /opt
RUN mkdir -p node_modules/esl/

WORKDIR /opt/node_modules/esl
COPY package.json yarn.lock .
RUN yarn --frozen-lockfile

RUN mkdir src/
COPY esl.d.ts build.mjs .
COPY src/* src/
RUN yarn build && rm -r node_modules/ src/ build.mjs yarn.lock

# Check
WORKDIR /opt
RUN ls -lR node_modules/esl/
COPY test/* test/
RUN yarn run coffee --bare -c test/*.litcoffee && (cd test && for f in *.js; do mv $f $(basename $f .js).mjs; done)
RUN for f in test/*.mjs; do echo $f; yarn run tsc \
      --allowJs --outDir dist --rootDir . --lib esnext --target esnext \
      --noEmit --strict --checkJs --moduleResolution nodenext -m nodenext \
      --noUnusedLocals --noUnusedParameters --strict --strictFunctionTypes \
      --strictNullChecks --noImplicitAny false $f; done
